@{
    RootModule = 'Specrew.psm1'
    ModuleVersion = '0.26.0'
    GUID = '8ad5b7b5-c4c6-4df4-b9bd-700a8533dcc4'
    Author = 'Alon Fliess'
    Description = 'Specrew: specification-driven development workflow for AI-augmented teams'
    PowerShellVersion = '7.0'
    CompatiblePSEditions = @('Core')
    FunctionsToExport = @(
        'Invoke-Specrew',
        'Initialize-Specrew',
        'Start-Specrew',
        'Update-Specrew',
        'Show-SpecrewVersion',
        'Show-SpecrewReview',
        'Invoke-SpecrewTeam',
        'Show-SpecrewStatus'
    )
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @(
        'specrew',
        'specrew-init',
        'specrew-start',
        'specrew-update',
        'specrew-version',
        'specrew-review',
        'specrew-team',
        'specrew-where'
    )
    FileList = @(
        'Specrew.psd1',
        'Specrew.psm1',
        'scripts/internal/coordinator-resume.ps1',
        'scripts/internal/dashboard-renderer.ps1',
        'scripts/internal/version-check.ps1',
        'scripts/internal/supported-versions.yml',
        'scripts/internal/sync-boundary-state.ps1',
        'scripts/internal/invoke-module-release.ps1',
        'scripts/internal/task-progress.ps1',
        'scripts/internal/worktree-awareness.ps1',
        'scripts/specrew-init.ps1',
        'scripts/specrew-review.ps1',
        'scripts/specrew-start.ps1',
        'scripts/specrew-team.ps1',
        'scripts/specrew-update.ps1',
        'scripts/specrew-version.ps1',
        'scripts/specrew-where.ps1',
        'scripts/specrew.ps1',
        'extensions/specrew-speckit/checklists/coordinator-handoff-governance.md',
        'extensions/specrew-speckit/commands/speckit.specrew-speckit.after-tasks.md',
        'extensions/specrew-speckit/commands/speckit.specrew-speckit.before-implement.md',
        'extensions/specrew-speckit/commands/speckit.specrew-speckit.before-plan.md',
        'extensions/specrew-speckit/commands/speckit.specrew-speckit.sync-clarify.md',
        'extensions/specrew-speckit/commands/speckit.specrew-speckit.sync-plan.md',
        'extensions/specrew-speckit/commands/speckit.specrew-speckit.sync-specify.md',
        'extensions/specrew-speckit/commands/speckit.specrew-speckit.sync-tasks.md',
        'extensions/specrew-speckit/design/soft-validator-handoff-governance.md',
        'extensions/specrew-speckit/extension.yml',
        'extensions/specrew-speckit/governance/validation-lane.md',
        'extensions/specrew-speckit/hooks/.gitkeep',
        'extensions/specrew-speckit/prompts/coordinator-decision-guidance.md',
        'extensions/specrew-speckit/prompts/coordinator-response.md',
        'extensions/specrew-speckit/README.md',
        'extensions/specrew-speckit/scripts/brownfield-merge.ps1',
        'extensions/specrew-speckit/scripts/collision-detect.ps1',
        'extensions/specrew-speckit/scripts/deploy-speckit-extension.ps1',
        'extensions/specrew-speckit/scripts/deploy-squad-runtime.ps1',
        'extensions/specrew-speckit/scripts/drift-diff.ps1',
        'extensions/specrew-speckit/scripts/manage-escalation-state.ps1',
        'extensions/specrew-speckit/scripts/manage-reviewer-regression.ps1',
        'extensions/specrew-speckit/scripts/resolve-quality-profile.ps1',
        'extensions/specrew-speckit/scripts/resume-iteration.ps1',
        'extensions/specrew-speckit/scripts/run-hardening-gate.ps1',
        'extensions/specrew-speckit/scripts/run-mechanical-checks.ps1',
        'extensions/specrew-speckit/scripts/scaffold-feature-closeout-dashboard.ps1',
        'extensions/specrew-speckit/scripts/scaffold-governance.ps1',
        'extensions/specrew-speckit/scripts/scaffold-iteration-artifacts.ps1',
        'extensions/specrew-speckit/scripts/scaffold-iteration-plan.ps1',
        'extensions/specrew-speckit/scripts/scaffold-retro-artifact.ps1',
        'extensions/specrew-speckit/scripts/scaffold-review-artifact.ps1',
        'extensions/specrew-speckit/scripts/scaffold-reviewer-artifacts.ps1',
        'extensions/specrew-speckit/scripts/shared-governance.ps1',
        'extensions/specrew-speckit/scripts/sync-squad-model-overrides.ps1',
        'extensions/specrew-speckit/scripts/sync-boundary-state.ps1',
        'extensions/specrew-speckit/scripts/Test-CopilotInstructionsChangeType.ps1',
        'extensions/specrew-speckit/scripts/validate-governance.ps1',
        'extensions/specrew-speckit/scripts/validate-versions.ps1',
        'extensions/specrew-speckit/squad-templates/README.md',
        'extensions/specrew-speckit/squad-templates/agents/implementer/charter.md',
        'extensions/specrew-speckit/squad-templates/agents/planner/charter.md',
        'extensions/specrew-speckit/squad-templates/agents/retro-facilitator/charter.md',
        'extensions/specrew-speckit/squad-templates/agents/reviewer/charter.md',
        'extensions/specrew-speckit/squad-templates/agents/spec-steward/charter.md',
        'extensions/specrew-speckit/squad-templates/ceremonies/README.md',
        'extensions/specrew-speckit/squad-templates/ceremonies/planning.md',
        'extensions/specrew-speckit/squad-templates/ceremonies/retro.md',
        'extensions/specrew-speckit/squad-templates/ceremonies/review-demo.md',
        'extensions/specrew-speckit/squad-templates/coordinator/specrew-governance.md',
        'extensions/specrew-speckit/squad-templates/directives/drift-reporting.md',
        'extensions/specrew-speckit/squad-templates/directives/README.md',
        'extensions/specrew-speckit/squad-templates/directives/spec-authority.md',
        'extensions/specrew-speckit/squad-templates/directives/traceability.md',
        'extensions/specrew-speckit/squad-templates/skills/README.md',
        'extensions/specrew-speckit/squad-templates/skills/capacity-planning.md',
        'extensions/specrew-speckit/squad-templates/skills/drift-check.md',
        'extensions/specrew-speckit/squad-templates/skills/iteration-resume.md',
        'extensions/specrew-speckit/squad-templates/skills/specrew-help/SKILL.md',
        'extensions/specrew-speckit/squad-templates/skills/specrew-review/SKILL.md',
        'extensions/specrew-speckit/squad-templates/skills/specrew-status/SKILL.md',
        'extensions/specrew-speckit/squad-templates/skills/specrew-team/SKILL.md',
        'extensions/specrew-speckit/squad-templates/skills/specrew-update/SKILL.md',
        'extensions/specrew-speckit/squad-templates/skills/specrew-version/SKILL.md',
        'extensions/specrew-speckit/squad-templates/skills/specrew-where/SKILL.md',
        'extensions/specrew-speckit/squad-templates/skills/traceability-check.md',
        'extensions/specrew-speckit/templates/downstream-constitution.md',
        'extensions/specrew-speckit/templates/iteration-config.yml',
        'extensions/specrew-speckit/templates/quality/README.md',
        'extensions/specrew-speckit/templates/quality/lenses/.gitkeep',
        'extensions/specrew-speckit/templates/quality/lenses/robustness-baseline-v1.md',
        'extensions/specrew-speckit/templates/quality/lenses/security-baseline-v1.md',
        'extensions/specrew-speckit/templates/quality/lenses/test-integrity-v1.md',
        'extensions/specrew-speckit/templates/quality/presets/.gitkeep',
        'extensions/specrew-speckit/templates/quality/presets/dotnet-aspnet-api-v1.md',
        'extensions/specrew-speckit/templates/quality/presets/node-public-ws-service-v1.md',
        'extensions/specrew-speckit/templates/quality/presets/node-rest-with-postgres-v1.md',
        'extensions/specrew-speckit/templates/quality/presets/python-fastapi-service-v1.md',
        'extensions/specrew-speckit/templates/quality/presets/react-spa-public-v1.md',
        'extensions/specrew-speckit/templates/role-assignments.yml',
        'extensions/specrew-speckit/validators/handoff-governance-validator.ps1',
        'templates/github/agents/squad.agent.md',
        'templates/github/workflows/specrew-ci.yml',
        'templates/github/workflows/specrew-confidence-lane.yml',
        'templates/github/workflows/specrew-project-sync.yml',
        'templates/specify/templates/agent-file-template.md',
        'templates/specify/templates/checklist-template.md',
        'templates/specify/templates/constitution-template.md',
        'templates/specify/templates/plan-template.md',
        'templates/specify/templates/spec-template.md',
        'templates/specify/templates/tasks-template.md',
        'templates/squad/agents/data/charter.md',
        'templates/squad/agents/data/history.md',
        'templates/squad/agents/implementer/charter.md',
        'templates/squad/agents/implementer/history.md',
        'templates/squad/agents/laforge/charter.md',
        'templates/squad/agents/laforge/history.md',
        'templates/squad/agents/picard/alignment-review-validator-fix.md',
        'templates/squad/agents/picard/charter.md',
        'templates/squad/agents/picard/history.md',
        'templates/squad/agents/planner/charter.md',
        'templates/squad/agents/planner/history.md',
        'templates/squad/agents/ralph/charter.md',
        'templates/squad/agents/ralph/history.md',
        'templates/squad/agents/retro-facilitator/charter.md',
        'templates/squad/agents/retro-facilitator/history.md',
        'templates/squad/agents/reviewer/charter.md',
        'templates/squad/agents/reviewer/history.md',
        'templates/squad/agents/scribe/charter.md',
        'templates/squad/agents/scribe/history.md',
        'templates/squad/agents/spec-steward/charter.md',
        'templates/squad/agents/spec-steward/history.md',
        'templates/squad/agents/troi/charter.md',
        'templates/squad/agents/troi/history.md',
        'templates/squad/agents/worf/charter.md',
        'templates/squad/agents/worf/history.md',
        'templates/squad/identity/now.md',
        'templates/squad/identity/wisdom.md',
        'docs/README.md',
        'docs/dashboard-guide.md',
        'docs/getting-started.md',
        'docs/github-project.md',
        'docs/roadmap-maintenance.md',
        'docs/user-guide.md',
        'docs/versioning.md',
        'docs/operations/psgallery-release-credentials.md'
    )
    PrivateData = @{
        PSData = @{
            Prerelease = ''
            Tags = @('specrew', 'specification', 'squad', 'ai-workflow', 'governance')
            ProjectUri = 'https://github.com/alonf/specrew'
            LicenseUri = 'https://github.com/alonf/specrew/blob/main/LICENSE'
            ReleaseNotes = 'https://github.com/alonf/specrew/blob/main/CHANGELOG.md'
        }
    }
}

